#!/usr/bin/env bash
# ==============================
# Local-Deploy - Install Script
# Installs local-deploy to a directory on PATH
# ==============================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Default install directory
DEFAULT_INSTALL_DIR="/usr/local/bin"
INSTALL_DIR="${1:-$DEFAULT_INSTALL_DIR}"

# Color codes
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo "============================================"
echo "  Local-Deploy - Installer"
echo "============================================"
echo ""

# Check if install directory exists
if [ ! -d "$INSTALL_DIR" ]; then
    echo -e "${RED}[ERROR]${NC} Install directory does not exist: ${INSTALL_DIR}"
    echo "Create it first or specify a different path: ./install.sh /your/path"
    exit 1
fi

# Check write permissions
if [ ! -w "$INSTALL_DIR" ]; then
    echo -e "${YELLOW}[WARN]${NC} No write permission to ${INSTALL_DIR}"
    echo "Try running with sudo: sudo ./install.sh"
    echo "Or install to a user directory: ./install.sh \$HOME/.local/bin"
    exit 1
fi

# Create a wrapper script that points to the actual installation
WRAPPER="${INSTALL_DIR}/local-deploy"

cat > "$WRAPPER" << EOF
#!/usr/bin/env bash
# Local-Deploy wrapper - auto-generated by install.sh
exec bash "${SCRIPT_DIR}/local-deploy.sh" "\$@"
EOF

chmod +x "$WRAPPER"

echo -e "${GREEN}[SUCCESS]${NC} local-deploy installed to: ${WRAPPER}"
echo ""
echo "Usage:"
echo "  local-deploy init      # Initialize a project"
echo "  local-deploy deploy    # Run build & deploy"
echo ""

# Check if the install dir is on PATH
if echo "$PATH" | tr ':' '\n' | grep -q "^${INSTALL_DIR}$"; then
    echo -e "${GREEN}[OK]${NC} ${INSTALL_DIR} is on your PATH."
else
    echo -e "${YELLOW}[WARN]${NC} ${INSTALL_DIR} is NOT on your PATH."
    echo "Add it by running:"
    echo "  export PATH=\"${INSTALL_DIR}:\$PATH\""
    echo "Or add the above line to your ~/.bashrc or ~/.zshrc"
fi

echo ""
